Repository COS301-SE-2021/GeoCode, pull requests merged in 2021-07, with the labels that each got.

#191 Add UNIQUE rarity type to the Rarity enum
  backend/src/main/java/tech/geocodeapp/geocode/collectable/model/Rarity.java
Labels: Collectable, enhancement

#192 Add correct ID's to Valid Tests
  backend/src/test/java/tech/geocodeapp/geocode/collectable/CollectableServiceImplIT.java
Labels: bug

#193 Cleaned GeoCode subsystem up
  backend/src/main/java/tech/geocodeapp/geocode/appglobal/RFC3339DateFormat.java
  backend/src/main/java/tech/geocodeapp/geocode/appglobal/swaggerui/CustomInstantDeserializer.java
  backend/src/main/java/tech/geocodeapp/geocode/appglobal/swaggerui/HomeController.java
  backend/src/main/java/tech/geocodeapp/geocode/appglobal/swaggerui/JacksonConfiguration.java
  backend/src/main/java/tech/geocodeapp/geocode/geocode/controller/GeoCodeApi.java
  backend/src/main/java/tech/geocodeapp/geocode/geocode/controller/GeoCodeApiController.java
  backend/src/main/java/tech/geocodeapp/geocode/geocode/model/GeoCode.java
  backend/src/main/java/tech/geocodeapp/geocode/geocode/request/CreateGeoCodeRequest.java
  backend/src/main/java/tech/geocodeapp/geocode/geocode/request/GetGeoCodeByLocationRequest.java
  backend/src/main/java/tech/geocodeapp/geocode/geocode/request/SwapCollectablesRequest.java
  backend/src/main/java/tech/geocodeapp/geocode/geocode/request/UpdateAvailabilityRequest.java
  backend/src/main/java/tech/geocodeapp/geocode/geocode/response/GetCollectablesResponse.java
  backend/src/main/java/tech/geocodeapp/geocode/geocode/response/GetGeoCodeByLocationResponse.java
  backend/src/main/java/tech/geocodeapp/geocode/geocode/response/GetGeoCodeByQRCodeResponse.java
  backend/src/main/java/tech/geocodeapp/geocode/geocode/service/GeoCodeService.java
  backend/src/main/java/tech/geocodeapp/geocode/geocode/service/GeoCodeServiceImpl.java
  backend/src/test/java/tech/geocodeapp/geocode/geocode/GeoCodeServiceImplIT.java
  backend/src/test/java/tech/geocodeapp/geocode/geocode/GeoCodeServiceImplTest.java
Labels: GeoCode, enhancement

#195 Created security checks
  .github/workflows/codacy-analysis.yml
  .github/workflows/codeql-analysis.yml
  .github/workflows/typescript.yml
  SECURITY.md
  frontend/karma.conf.js
  frontend/package-lock.json
  frontend/package.json
  frontend/src/environments/environment.prod.ts
Labels: enhancement

#210 Fixed sonarcloud issues
  .github/workflows/codacy-analysis.yml
  backend/src/main/java/tech/geocodeapp/geocode/appglobal/security/KeycloakSecurityConfig.java
  backend/src/main/java/tech/geocodeapp/geocode/geocode/response/GetCollectablesResponse.java
  backend/src/main/java/tech/geocodeapp/geocode/geocode/service/GeoCodeServiceImpl.java
  backend/src/main/java/tech/geocodeapp/geocode/user/response/GetCurrentCollectableResponse.java
  backend/src/test/java/tech/geocodeapp/geocode/geocode/GeoCodeServiceImplTest.java
Labels: GeoCode, bug

#216 Dev/app events pages
  frontend/src/app/tabs/events/event-leaderboard/event-leaderboard-routing.module.ts
  frontend/src/app/tabs/events/event-leaderboard/event-leaderboard.module.ts
  frontend/src/app/tabs/events/event-leaderboard/event-leaderboard.page.html
  frontend/src/app/tabs/events/event-leaderboard/event-leaderboard.page.scss
  frontend/src/app/tabs/events/event-leaderboard/event-leaderboard.page.spec.ts
  frontend/src/app/tabs/events/event-leaderboard/event-leaderboard.page.ts
  frontend/src/app/tabs/events/event-timetrial/event-timetrial-routing.module.ts
  frontend/src/app/tabs/events/event-timetrial/event-timetrial.module.ts
  frontend/src/app/tabs/events/event-timetrial/event-timetrial.page.html
  frontend/src/app/tabs/events/event-timetrial/event-timetrial.page.scss
  frontend/src/app/tabs/events/event-timetrial/event-timetrial.page.spec.ts
  frontend/src/app/tabs/events/event-timetrial/event-timetrial.page.ts
  frontend/src/app/tabs/events/events-routing.module.ts
Labels: Event, Styling

#218 Created new colours for colour scheme for both light and dark mode
  frontend/src/theme/variables.scss
Labels: Application, Styling

#220 Dev/app geocode
  frontend/src/app/tabs/geocode/geocode.page.html
  frontend/src/app/tabs/geocode/geocode.page.scss
  frontend/src/app/tabs/geocode/geocode.page.ts
  frontend/src/app/tabs/tabs.page.scss
Labels: Application, Styling

#230 Changed google maps to use library
  frontend/src/app/tabs/events/event-timetrial/event-timetrial.page.ts
Labels: Application
